name: Main Terraform Trigger

on:
  pull_request:
    branches:
      - main

jobs:
  call-terraform-workflow:
    name: Call Terraform Workflow
    uses: ./.github/workflows/terraform.yml
    with:
      path: AUY1105-Infraestructura-como-codigo-II/EA1/ACT1.7/